# AgentCleanser pipeline: https://dev.azure.com/xamarin/public/_apps/hub/ms.vss-ciworkflow.build-ci-hub?_a=edit-build-definition&id=69&view=Tab_Tasks

parameters:
- name: AgentPool
  displayName: Agent pool
  type: string
  default: MAUI
  values:
  - MAUI                          # https://dev.azure.com/xamarin/public/_settings/agentqueues?queueId=96&view=agents
  - MAUI-Testing                  # https://dev.azure.com/xamarin/public/_settings/agentqueues?queueId=100&view=agents

- name: YamlTemplatesBranch
  type: string
  default: "refs/heads/main"

- name: WaitTime
  displayName: Job wait time (seconds)
  type: number
  default: 0

- name: AgentName
  displayName: Agent name
  type: string
  default: Any

- name: RebootAgent
  type: boolean
  default: false

- name: MacOS
  displayName: Mac OS
  type: string
  default: Sonoma
  values:
  - Any
  - Sonoma
  - Sequoia

- name: MacArchitecture
  displayName: Mac architecture
  type: string
  default: arm64
  values:
  - x64
  - arm64

- name: CleanseProcesses
  type: boolean
  default: false

- name: TeminateSimulators
  type: boolean
  default: true

- name: TerminatePopups
  type: boolean
  default: false

- name: UninstallMono
  type: boolean
  default: true

- name: UninstallXamarinMac
  type: boolean
  default: true

- name: CleanseProvisionatorCache
  type: boolean
  default: true

- name: CleanseXcodeArchives
  type: boolean
  default: true

- name: CleanseAgentToolsDotNet
  type: boolean
  default: false

- name: CleanseAgentRebooter
  type: boolean
  default: true

- name: CheckBrewInstall
  type: boolean
  default: false

- name: InstallBrewPackages
  type: boolean
  default: false

- name: BrewPackagesToInstall
  type: string
  default: " " # Parameters can't be empty, but whitespace is treated as an empty string

- name: Provision
  type: boolean
  default: false

- name: provisionatorChannel
  displayName: 'Provisionator channel'
  type: string
  default: 'latest'           # Support for launching a build against a Provisionator PR (e.g., pr/[github-account-name]/[pr-number]) as a means to test in-progress Provisionator changes

- name: ProvisioningScript
  displayName: 'Provisioning script'
  type: string
  default: 'provision.csx'

resources:
  repositories:
  - repository: self
    checkoutOptions:
      submodules: false

  - repository: templates
    type: github
    name: xamarin/yaml-templates
    ref: ${{ parameters.YamlTemplatesBranch }}
    endpoint: xamarin

variables:
# UNDONE: Onboard DDBotDeploy
#  - group: DDBotDeploy Secrets    # https://devdiv.visualstudio.com/DefaultCollection/Engineering/_library?itemType=VariableGroups&view=VariableGroupView&variableGroupId=579&path=DDBotDeploy%20Secrets
  - name: system.debug
    value: false

trigger:
- main

jobs:
- job: AgentCleanser
  timeoutInMinutes: 60
  pool:
    ${{ if eq(parameters.AgentPool, 'Hosted-MacOS-14') }}:
      name: 'Azure Pipelines'
      vmImage: macOS-14           # https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml
    ${{ elseif eq(parameters.AgentPool, 'Hosted-MacOS-13') }}:
      name: 'Azure Pipelines'
      vmImage: macOS-13           # https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml
    ${{ elseif eq(parameters.AgentPool, 'Hosted-Windows-2022') }}:
      name: 'Azure Pipelines'
      vmImage: Windows-2022       # https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml
    ${{ else }}:
      name: ${{ parameters.AgentPool }}
      ${{ if ne(parameters.AgentName, 'Any') }}:
        demands:
        - Agent.Name -equals ${{ parameters.AgentName }}
      ${{ if and(eq(parameters.AgentName, 'Any'), ne(parameters.MacOS, 'Any')) }}:
        demands:
        - macOS.Name -equals ${{ parameters.MacOS }}
        - macOS.Architecture -equals ${{ parameters.MacArchitecture }}
  workspace:
    clean: all  # Note: $(Agent.TempDirectory) is cleaned between every job

  steps:
  - checkout: self          # https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#checkout
    clean: true             # Executes: git clean -ffdx && git reset --hard HEAD
    submodules: recursive

  - powershell: |
      Write-Host "Agent.Name: $(Agent.Name)"
    displayName: 'Show Agent.Name'

  # The following steps are designed for Mac agents only
  - ${{ if not(startswith(parameters.AgentPool, 'Hosted-Windows-')) }}:
    - bash: |
        # https://stackoverflow.com/questions/23934425/parse-ifconfig-to-get-only-my-ip-address-using-bash

        en0ip=$(ifconfig en0 | awk '{ print $2 }' | grep -E -o "([0-9]{1,3}[\.]){3}[0-9]{1,3}")
        if [[ -n $en0ip ]]; then
          echo $en0ip
        fi

        en1ip=$(ifconfig en1 | awk '{ print $2 }' | grep -E -o "([0-9]{1,3}[\.]){3}[0-9]{1,3}")
        if [[ -n $en1ip ]]; then
          echo $en1ip
        fi
      failOnStderr: false
      workingDirectory: $(Build.SourcesDirectory)
      displayName: 'Show IP address'

    - bash: |
        buildStagingDirectory="$(Build.ArtifactStagingDirectory)"
        echo "Build.ArtifactStagingDirectory: ${buildStagingDirectory}"

        pkgInfoDirectory="${buildStagingDirectory}/pkg.info"
        echo "Package info directory: ${pkgInfoDirectory}"

        if [[ ! -d $pkgInfoDirectory ]]; then
          echo "Creating ${pkgInfoDirectory}"
          mkdir $pkgInfoDirectory
        fi

        # Show brew location
        echo
        which brew

        topLevelPackagesPathAndFilename="${pkgInfoDirectory}/${HOSTNAME}.BrewPackages.TopLevel.txt"
        allPackagesPathAndFilename="${pkgInfoDirectory}/${HOSTNAME}.BrewPackages.All.txt"

        echo
        echo "--------------------------------------------------------------------------------"
        echo "Brew installed (top-level) packages"
        echo "--------------------------------------------------------------------------------"
        brew leaves > $topLevelPackagesPathAndFilename
        cat $topLevelPackagesPathAndFilename

        echo
        echo "--------------------------------------------------------------------------------"
        echo "All brew packages"
        echo "--------------------------------------------------------------------------------"
        brew list --versions > $allPackagesPathAndFilename
        cat $allPackagesPathAndFilename
      failOnStderr: false
      displayName: 'Show brew packages'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish BrewPackages.txt'
      inputs:
        artifactName: brew.packages
        pathToPublish: '$(Build.ArtifactStagingDirectory)/pkg.info'

    - template: agent-cleanser/v1.yml@templates
      parameters:
        CleanseProcesses: ${{ parameters.CleanseProcesses }}
        SelfHealPowerShell: false                                                 # This is the only cleansing activity that requires GitHub.Token and so avoid using it
        TeminateSimulators: ${{ parameters.TeminateSimulators }}
        TerminatePopups: ${{ parameters.TerminatePopups }}
        UninstallMono: ${{ parameters.UninstallMono }}
        UninstallXamarinMac: ${{ parameters.UninstallXamarinMac }}
        CleanseProvisionatorCache: ${{ parameters.CleanseProvisionatorCache }}
        CleanseXcodeArchives: ${{ parameters.CleanseXcodeArchives }}
        CleanseAgentToolsDotNet: ${{ parameters.CleanseAgentToolsDotNet }}
        CleanseAgentRebooter: ${{ parameters.CleanseAgentRebooter }}
        CheckBrewInstall: ${{ parameters.CheckBrewInstall }}
        InstallBrewPackages: ${{ parameters.InstallBrewPackages }}
        BrewPackagesToInstall: ${{ parameters.BrewPackagesToInstall }}

    - ${{ if gt(parameters.WaitTime, 0) }}:
      - powershell: |
          $waitTime = ${{ parameters.WaitTime }}
          Write-Host "Wait time: ${waitTime}"
          Start-Sleep $waitTime
        displayName: 'Wait: Opportunity to cleanse other agents'

    - ${{ if eq(parameters.RebootAgent, true) }}:
      - powershell: |
          $functionKey = "$(Rebooter.FunctionKey)"
          $functionKeyPartial = $functionKey.SubString(0, 8)
          Write-Host "Function key (hint): ${functionKeyPartial}"
        displayName: 'Show function key hint'

      - template: agent-rebooter/mac.v1.yml@templates
        parameters:
          AgentMonitor_FunctionKey: $(Rebooter.FunctionKey)            # Rebooter.FunctionKey needs to be defined as a pipeline variable
          AgentMonitor_PoolEndPoint: https://agentmonitor2-test.azurewebsites.net/api/Pool
          AgentMonitor_AgentEndPoint: https://agentmonitor2-test.azurewebsites.net/api/Agent

      - powershell: |
          function Stage-File([string] $ScriptsStagingDirectory, [string] $PathAndFilename) {
              $scriptExists = $false
              if ([IO.File]::Exists($PathAndFilename)) {
                  $scriptExists = $true
                  $filename = [IO.Path]::GetFileName($PathAndFilename)
                  $stagingPathAndFilename = [IO.Path]::Combine($ScriptsStagingDirectory, $filename)
                  Write-Host "Copying '${PathAndFilename}' to '${stagingPathAndFilename}'"
                  [IO.File]::Copy($PathAndFilename, $stagingPathAndFilename)
              } else {
                  Write-Host "WARNING: File not found: ${PathAndFilename}"
              }
              return $scriptExists
          }

          $stagingDirectory = "$(Build.ArtifactStagingDirectory)"
          $scriptsStagingDirectory = [IO.Path]::Combine($stagingDirectory, 'scripts')
          Write-Host "Build.ArtifactStagingDirectory: ${stagingDirectory}"
          Write-Host "Scripts staging directory: ${scriptsStagingDirectory}"

          if (-not ([IO.Directory]::Exists($scriptsStagingDirectory))) {
            Write-Host "Creating directory: ${scriptsStagingDirectory}"
            [IO.Directory]::CreateDirectory($scriptsStagingDirectory)
          }

          $scriptsExist = $false
          $user = $env:USER
          $rebooterPath = "/Users/${user}/Agent.Rebooter"

          Write-Host "User: ${user}"
          Write-Host "Rebooter path: ${rebooterPath}"

          if ([IO.Directory]::Exists($rebooterPath)) {
            $files = @('enable-agent.bootstrapper.sh', 'EnableAgent.ps1', 'com.enable.agent2.plist', 'com.reboot.agent.plist')
            $files | foreach {
              $pathAndFilename = [IO.Path]::Combine($rebooterPath, $_)
              $scriptExists = Stage-File -ScriptsStagingDirectory $scriptsStagingDirectory -PathAndFilename $pathAndFilename
              $scriptsExist = $scriptsExist -or $scriptExists
            }
          } else {
            Write-Host "WARNING: Agent-Rebooter script staging skipped. Rebooter path does not exist"
          }

          Write-Host "Setting Publish.Scripts: ${scriptsExist}"
          Write-Host "Setting Scripts.Directory: ${scriptsStagingDirectory}"
          Write-Host "##vso[task.setvariable variable=Publish.Scripts]${scriptsExist}"
          Write-Host "##vso[task.setvariable variable=Scripts.Directory]${scriptsStagingDirectory}"
        displayName: 'Stage agent-rebooter scripts'

      - task: PublishBuildArtifacts@1
        displayName: 'Publish: Agent-Rebooter scripts'
        condition: and(succeeded(), eq(variables['Publish.Scripts'], 'true'))
        inputs:
          artifactName: rebooter.scripts
          pathToPublish: $(Scripts.Directory)

